let fullMatchArray = [
  {
    matchNumber: 1,
    topLineWrestler: { name: "Wrestler Seeded1", team: "Team 1" },
    bottomLineWrestler: { name: "Wrestler Seeded2", team: "Team 2" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 2,
    topLineWrestler: { name: "Wrestler Seeded3", team: "Team 3" },
    bottomLineWrestler: { name: "Wrestler Seeded4", team: "Team 4" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 3,
    topLineWrestler: { name: "Wrestler Seeded5", team: "Team 5" },
    bottomLineWrestler: { name: "Wrestler Seeded6", team: "Team 6" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 4,
    topLineWrestler: { name: "Wrestler Seeded7", team: "Team 7" },
    bottomLineWrestler: { name: "Wrestler Seeded8", team: "Team 8" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 5,
    topLineWrestler: { name: "Wrestler Seeded9", team: "Team 9" },
    bottomLineWrestler: { name: "Wrestler Seeded10", team: "Team 10" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 6,
    topLineWrestler: { name: "Wrestler Seeded11", team: "Team 11" },
    bottomLineWrestler: { name: "Wrestler Seeded12", team: "Team 12" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 7,
    topLineWrestler: { name: "Wrestler Seeded13", team: "Team 13" },
    bottomLineWrestler: { name: "Wrestler Seeded14", team: "Team 14" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 8,
    topLineWrestler: { name: "Wrestler Seeded15", team: "Team 15" },
    bottomLineWrestler: { name: "Wrestler Seeded16", team: "Team 16" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 9,
    topLineWrestler: { name: "Wrestler Seeded17", team: "Team 17" },
    bottomLineWrestler: { name: "Wrestler Seeded18", team: "Team 18" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 10,
    topLineWrestler: { name: "Wrestler Seeded19", team: "Team 19" },
    bottomLineWrestler: { name: "Wrestler Seeded20", team: "Team 20" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 11,
    topLineWrestler: { name: "Wrestler Seeded21", team: "Team 21" },
    bottomLineWrestler: { name: "Wrestler Seeded22", team: "Team 22" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 12,
    topLineWrestler: { name: "Wrestler Seeded23", team: "Team 23" },
    bottomLineWrestler: { name: "Wrestler Seeded24", team: "Team 24" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 13,
    topLineWrestler: { name: "Wrestler Seeded25", team: "Team 25" },
    bottomLineWrestler: { name: "Wrestler Seeded26", team: "Team 26" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 14,
    topLineWrestler: { name: "Wrestler Seeded27", team: "Team 27" },
    bottomLineWrestler: { name: "Wrestler Seeded28", team: "Team 28" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 15,
    topLineWrestler: { name: "Wrestler Seeded29", team: "Team 29" },
    bottomLineWrestler: { name: "Wrestler Seeded30", team: "Team 30" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 16,
    topLineWrestler: { name: "Wrestler Seeded31", team: "Team 31" },
    bottomLineWrestler: { name: "Wrestler Seeded32", team: "Team 32" },
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 1,
  },
  {
    matchNumber: 17,
    topLineWrestler: "loserOfBout#1",
    bottomLineWrestler: "loserOfBout#2",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 2,
  },
  {
    matchNumber: 18,
    topLineWrestler: "loserOfBout#3",
    bottomLineWrestler: "loserOfBout#4",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 2,
  },
  {
    matchNumber: 19,
    topLineWrestler: "loserOfBout#5",
    bottomLineWrestler: "loserOfBout#6",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 2,
  },
  {
    matchNumber: 20,
    topLineWrestler: "loserOfBout#7",
    bottomLineWrestler: "loserOfBout#8",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 2,
  },
  {
    matchNumber: 21,
    topLineWrestler: "loserOfBout#9",
    bottomLineWrestler: "loserOfBout#10",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 2,
  },
  {
    matchNumber: 22,
    topLineWrestler: "loserOfBout#11",
    bottomLineWrestler: "loserOfBout#12",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 2,
  },
  {
    matchNumber: 23,
    topLineWrestler: "loserOfBout#13",
    bottomLineWrestler: "loserOfBout#14",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 2,
  },
  {
    matchNumber: 24,
    topLineWrestler: "loserOfBout#15",
    bottomLineWrestler: "loserOfBout#16",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 2,
  },
  {
    matchNumber: 25,
    topLineWrestler: "winnerOfBout#1",
    bottomLineWrestler: "winnerOfBout#2",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 3,
  },
  {
    matchNumber: 26,
    topLineWrestler: "winnerOfBout#3",
    bottomLineWrestler: "winnerOfBout#4",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 3,
  },
  {
    matchNumber: 27,
    topLineWrestler: "winnerOfBout#5",
    bottomLineWrestler: "winnerOfBout#6",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 3,
  },
  {
    matchNumber: 28,
    topLineWrestler: "winnerOfBout#7",
    bottomLineWrestler: "winnerOfBout#8",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 3,
  },
  {
    matchNumber: 29,
    topLineWrestler: "winnerOfBout#9",
    bottomLineWrestler: "winnerOfBout#10",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 3,
  },
  {
    matchNumber: 30,
    topLineWrestler: "winnerOfBout#11",
    bottomLineWrestler: "winnerOfBout#12",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 3,
  },
  {
    matchNumber: 31,
    topLineWrestler: "winnerOfBout#13",
    bottomLineWrestler: "winnerOfBout#14",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 3,
  },
  {
    matchNumber: 32,
    topLineWrestler: "winnerOfBout#15",
    bottomLineWrestler: "winnerOfBout#16",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 3,
  },
  {
    matchNumber: 33,
    topLineWrestler: "winnerOfBout#17",
    bottomLineWrestler: "loserOfBout#32",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 4,
  },
  {
    matchNumber: 34,
    topLineWrestler: "winnerOfBout#18",
    bottomLineWrestler: "loserOfBout#31",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 4,
  },
  {
    matchNumber: 35,
    topLineWrestler: "winnerOfBout#19",
    bottomLineWrestler: "loserOfBout#30",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 4,
  },
  {
    matchNumber: 36,
    topLineWrestler: "winnerOfBout#20",
    bottomLineWrestler: "loserOfBout#29",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 4,
  },
  {
    matchNumber: 37,
    topLineWrestler: "winnerOfBout#21",
    bottomLineWrestler: "loserOfBout#28",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 4,
  },
  {
    matchNumber: 38,
    topLineWrestler: "winnerOfBout#22",
    bottomLineWrestler: "loserOfBout#27",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 4,
  },
  {
    matchNumber: 39,
    topLineWrestler: "winnerOfBout#23",
    bottomLineWrestler: "loserOfBout#26",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 4,
  },
  {
    matchNumber: 40,
    topLineWrestler: "winnerOfBout#24",
    bottomLineWrestler: "loserOfBout#25",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 4,
  },
  {
    matchNumber: 41,
    topLineWrestler: "winnerOfBout#25",
    bottomLineWrestler: "winnerOfBout#26",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 5,
  },
  {
    matchNumber: 42,
    topLineWrestler: "winnerOfBout#27",
    bottomLineWrestler: "winnerOfBout#28",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 5,
  },
  {
    matchNumber: 43,
    topLineWrestler: "winnerOfBout#29",
    bottomLineWrestler: "winnerOfBout#30",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 5,
  },
  {
    matchNumber: 44,
    topLineWrestler: "winnerOfBout#31",
    bottomLineWrestler: "winnerOfBout#32",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 5,
  },
  {
    matchNumber: 45,
    topLineWrestler: "winnerOfBout#33",
    bottomLineWrestler: "winnerOfBout#34",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 6,
  },
  {
    matchNumber: 46,
    topLineWrestler: "winnerOfBout#35",
    bottomLineWrestler: "winnerOfBout#36",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 6,
  },
  {
    matchNumber: 47,
    topLineWrestler: "winnerOfBout#37",
    bottomLineWrestler: "winnerOfBout#38",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 6,
  },
  {
    matchNumber: 48,
    topLineWrestler: "winnerOfBout#39",
    bottomLineWrestler: "winnerOfBout#40",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 6,
  },
  {
    matchNumber: 49,
    topLineWrestler: "winnerOfBout#45",
    bottomLineWrestler: "loserOfBout#42",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 7,
  },
  {
    matchNumber: 50,
    topLineWrestler: "winnerOfBout#46",
    bottomLineWrestler: "loserOfBout#41",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 7,
  },
  {
    matchNumber: 51,
    topLineWrestler: "winnerOfBout#47",
    bottomLineWrestler: "loserOfBout#44",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 7,
  },
  {
    matchNumber: 52,
    topLineWrestler: "winnerOfBout#48",
    bottomLineWrestler: "loserOfBout#43",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 7,
  },
  {
    matchNumber: 53,
    topLineWrestler: "winnerOfBout#41",
    bottomLineWrestler: "winnerOfBout#42",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 8,
  },
  {
    matchNumber: 54,
    topLineWrestler: "winnerOfBout#43",
    bottomLineWrestler: "winnerOfBout#44",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 8,
  },
  {
    matchNumber: 55,
    topLineWrestler: "winnerOfBout#49",
    bottomLineWrestler: "winnerOfBout#50",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 9,
  },
  {
    matchNumber: 56,
    topLineWrestler: "winnerOfBout#51",
    bottomLineWrestler: "winnerOfBout#52",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 9,
  },
  {
    matchNumber: 57,
    topLineWrestler: "winnerOfBout#55",
    bottomLineWrestler: "loserOfBout#54",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 10,
  },
  {
    matchNumber: 58,
    topLineWrestler: "winnerOfBout#56",
    bottomLineWrestler: "loserOfBout#53",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 10,
  },
  {
    matchNumber: 59,
    topLineWrestler: "winnerOfBout#53",
    bottomLineWrestler: "winnerOfBout#54",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 11,
  },
  {
    matchNumber: 60,
    topLineWrestler: "winnerOfBout#57",
    bottomLineWrestler: "winnerOfBout#58",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 12,
  },
  {
    matchNumber: 61,
    topLineWrestler: "loserOfBout#57",
    bottomLineWrestler: "loserOfBout#58",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 12,
  },
  {
    matchNumber: 62,
    topLineWrestler: "loserOfBout#55",
    bottomLineWrestler: "loserOfBout#56",
    winner: null,
    loser: null,
    score: null,
    dispatched: false,
    round: 12,
  },
];

//With this system we will have to manuualy submit each match to a mat, but we will always have unlimited digital mats.
let dispatch = (matchNumber, matNumber) => {
  for (let x = 0; x < fullMatchArray.length; x++) {
    if (matchNumber === fullMatchArray[x].matchNumber) {
      fullMatchArray[x].dispatched = true;
      fullMatchArray[x].dispatchedToMat = matNumber;
    }
  }
};

dispatch(1, 1);
dispatch(2, 2);
dispatch(3, 1);

let submitResult = (matchNumber, winner, loser, score) => {
  for (let x = 0; x < fullMatchArray.length; x++) {
    if (fullMatchArray[x].matchNumber === matchNumber) {
      fullMatchArray[x].winner = winner;
      fullMatchArray[x].loser = loser;
      fullMatchArray[x].score = score;
      fullMatchArray[x].dispatched = false;

      //This will update the matches that are dependent upon the result:
      for (let y = 0; y < fullMatchArray.length; y++) {
        //I'm a little hesitant on my slopiness of the string concatenation below (relying on JS to coerce the number into a string). Hopefully it doesn't come back to haunt me.
        if (
          fullMatchArray[y].topLineWrestler ===
          "winnerOfBout#" + matchNumber
        ) {
          fullMatchArray[y].topLineWrestler = winner;
          fullMatchArray[y].topLineWrestlersPreviousResult = score;
        }
        if (
          fullMatchArray[y].topLineWrestler ===
          "loserOfBout#" + matchNumber
        ) {
          fullMatchArray[y].topLineWrestler = loser;
          fullMatchArray[y].topLineWrestlersPreviousResult = score;
        }
        if (
          fullMatchArray[y].bottomLineWrestler ===
          "winnerOfBout#" + matchNumber
        ) {
          fullMatchArray[y].bottomLineWrestler = winner;
          fullMatchArray[y].bottomLineWrestlersPreviousResult = score;
        }
        if (
          fullMatchArray[y].bottomLineWrestler ===
          "loserOfBout#" + matchNumber
        ) {
          fullMatchArray[y].bottomLineWrestler = loser;
          fullMatchArray[y].bottomLineWrestlersPreviousResult = score;
        }
      }
    }
  }
};

submitResult(1, "turdman", "turdgirl", "pin 3:21");
submitResult(2, "yeast fest", "nope", "tech 0:21");

console.log(fullMatchArray);
